file_date_format: "%d%m%Y%H%M%S"

missions:
  1: ORBONE
  2: CLNM
  3: TMRS
  4: GALXONE
  5: UNKN

device_status:
  1: excellent
  2: good
  3: warning
  4: faulty
  5: killed
  6: unknown

random_number_files:
  inicial: 1
  final: 100

second_interval: 5

content_file:
  date:
  device_status:
  device_type:
  hash:
  mission: