[tool.poetry]
name = "demo"
version = "0.1.0"
description = ""
authors = ["Maria Franco <mafa1008@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
